<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'age' => [parent::class, 'age', null],
        "\0".parent::class."\0".'difficulte' => [parent::class, 'difficulte', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'genre' => [parent::class, 'genre', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'id_fils' => [parent::class, 'id_fils', null],
        "\0".parent::class."\0".'niv_difficulte' => [parent::class, 'niv_difficulte', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'num_tel' => [parent::class, 'num_tel', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null],
        "\0".parent::class."\0".'specialite' => [parent::class, 'specialite', null],
        'age' => [parent::class, 'age', null],
        'difficulte' => [parent::class, 'difficulte', null],
        'email' => [parent::class, 'email', null],
        'genre' => [parent::class, 'genre', null],
        'id' => [parent::class, 'id', null],
        'id_fils' => [parent::class, 'id_fils', null],
        'niv_difficulte' => [parent::class, 'niv_difficulte', null],
        'nom' => [parent::class, 'nom', null],
        'num_tel' => [parent::class, 'num_tel', null],
        'password' => [parent::class, 'password', null],
        'prenom' => [parent::class, 'prenom', null],
        'role' => [parent::class, 'role', null],
        'specialite' => [parent::class, 'specialite', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
