<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTkaxqyR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTkaxqyR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTkaxqyR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTkaxqyR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTkaxqyR\App_KernelDevDebugContainer([
    'container.build_hash' => 'TkaxqyR',
    'container.build_id' => '60308dba',
    'container.build_time' => 1739740413,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTkaxqyR');
