<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTj5Wy1Y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTj5Wy1Y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTj5Wy1Y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTj5Wy1Y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTj5Wy1Y\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tj5Wy1Y',
    'container.build_id' => 'ed00be5b',
    'container.build_time' => 1739748129,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTj5Wy1Y');
