<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSkxzvtz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSkxzvtz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSkxzvtz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSkxzvtz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSkxzvtz\App_KernelDevDebugContainer([
    'container.build_hash' => 'Skxzvtz',
    'container.build_id' => '4205b1ad',
    'container.build_time' => 1739652309,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSkxzvtz');
