<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_admin' => [[], ['_controller' => 'App\\Controller\\AdminController::admin'], [], [['text', '/admin']], [], [], []],
    'app_cours' => [[], ['_controller' => 'App\\Controller\\CoursController::index'], [], [['text', '/cours']], [], [], []],
    'app_detailscours' => [['id'], ['_controller' => 'App\\Controller\\CoursController::show'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/cours']], [], [], []],
    'course_new' => [[], ['_controller' => 'App\\Controller\\CoursController::add'], [], [['text', '/cours/new']], [], [], []],
    'course_edit' => [['id'], ['_controller' => 'App\\Controller\\CoursController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/cours']], [], [], []],
    'course_delete' => [['id'], ['_controller' => 'App\\Controller\\CoursController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/cours']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/home']], [], [], []],
    'app_signup' => [[], ['_controller' => 'App\\Controller\\SignupController::signup'], [], [['text', '/signup']], [], [], []],
    'App\Controller\AdminController::admin' => [[], ['_controller' => 'App\\Controller\\AdminController::admin'], [], [['text', '/admin']], [], [], []],
    'App\Controller\CoursController::index' => [[], ['_controller' => 'App\\Controller\\CoursController::index'], [], [['text', '/cours']], [], [], []],
    'App\Controller\CoursController::show' => [['id'], ['_controller' => 'App\\Controller\\CoursController::show'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/cours']], [], [], []],
    'App\Controller\CoursController::add' => [[], ['_controller' => 'App\\Controller\\CoursController::add'], [], [['text', '/cours/new']], [], [], []],
    'App\Controller\CoursController::edit' => [['id'], ['_controller' => 'App\\Controller\\CoursController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/cours']], [], [], []],
    'App\Controller\CoursController::delete' => [['id'], ['_controller' => 'App\\Controller\\CoursController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/cours']], [], [], []],
    'App\Controller\DefaultController::index' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/home']], [], [], []],
    'App\Controller\SignupController::signup' => [[], ['_controller' => 'App\\Controller\\SignupController::signup'], [], [['text', '/signup']], [], [], []],
];
